apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: ip-pool-1
  namespace: default
  labels:
    cluster.x-k8s.io/ip-pool-group: YOUR_IP_POOL_GROUP_NAME
    cluster.x-k8s.io/network-name: YOUR_NETWORK_NAME
spec:
  pools:
    - start: YOUR_INPUT_IP
      end: YOUR_INPUT_IP
      prefix: YOUR_MASK
      gateway: YOUR_GATEWAY
  prefix: YOUR_MASK
  gateway: YOUR_GATEWAY
  namePrefix: YOUR_NAME_PREFIX
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfCluster
metadata:
  name: mycluster
  namespace: default
  labels:
    cluster.x-k8s.io/ip-pool-group: YOUR_IP_POOL_GROUP_NAME
    cluster.x-k8s.io/network-name: YOUR_NETWORK_NAME
spec:
  controlPlaneEndpoint:
    host: ""
    port: 6443
